FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY external-service-mock/ .
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app .
USER $APP_UID
ENTRYPOINT ["dotnet", "ExternalServiceMock.dll"]
